import type { Game } from "@/types";

export const GAMES: Game[] = [
  {
    slug: "pokemon",
    name: "Pokemon",
    emoji: "P",
    color: "#f59e0b",
    bgColor: "#fef3c7",
    description: "Cartas, sobres, colecciones y accesorios Pokemon TCG",
    categorySlug: "pokemon",
  },
  {
    slug: "magic",
    name: "Magic: The Gathering",
    emoji: "M",
    color: "#7c3aed",
    bgColor: "#ede9fe",
    description: "Cartas singles, mazos, sets y colecciones de Magic",
    categorySlug: "magic",
  },
  {
    slug: "yugioh",
    name: "Yu-Gi-Oh!",
    emoji: "Y",
    color: "#dc2626",
    bgColor: "#fee2e2",
    description: "Cartas, estructuras y colecciones de Yu-Gi-Oh!",
    categorySlug: "yugioh",
  },
  {
    slug: "naruto",
    name: "Naruto",
    emoji: "N",
    color: "#ea580c",
    bgColor: "#ffedd5",
    description: "Cartas y colecciones del TCG de Naruto",
    categorySlug: "naruto",
  },
  {
    slug: "lorcana",
    name: "Lorcana",
    emoji: "L",
    color: "#0891b2",
    bgColor: "#cffafe",
    description: "Cartas, sobres y sets de Disney Lorcana",
    categorySlug: "lorcana",
  },
  {
    slug: "dragon-ball",
    name: "Dragon Ball Super CG",
    emoji: "D",
    color: "#d97706",
    bgColor: "#fef3c7",
    description: "Cartas y sets del Dragon Ball Super Card Game",
    categorySlug: "dragon-ball",
  },
];

export const STORES = [
  {
    id: "calpe",
    name: "TCG Academy Calpe",
    city: "Calpe, Alicante",
    address: "Av. Gabriel Miro 42, 03710 Calpe",
    phone: "+34 965 000 001",
    email: "calpe@tcgacademy.es",
    hours: "L-V 10:00-20:00 | S-D 10:00-14:00",
    mapUrl: "https://maps.google.com/?q=Calpe+Alicante",
    color: "#1a3a5c",
  },
  {
    id: "bejar",
    name: "TCG Academy Bejar",
    city: "Bejar, Salamanca",
    address: "C/ Mayor 15, 37700 Bejar",
    phone: "+34 923 000 002",
    email: "bejar@tcgacademy.es",
    hours: "L-V 10:00-20:00 | S 10:00-14:00",
    mapUrl: "https://maps.google.com/?q=Bejar+Salamanca",
    color: "#2d6a9f",
  },
  {
    id: "madrid",
    name: "TCG Academy Madrid",
    city: "Madrid",
    address: "C/ Gran Via 28, 28013 Madrid",
    phone: "+34 910 000 003",
    email: "madrid@tcgacademy.es",
    hours: "L-S 10:00-21:00 | D 11:00-19:00",
    mapUrl: "https://maps.google.com/?q=Gran+Via+Madrid",
    color: "#dc2626",
  },
  {
    id: "barcelona",
    name: "TCG Academy Barcelona",
    city: "Barcelona",
    address: "C/ Pelai 12, 08001 Barcelona",
    phone: "+34 930 000 004",
    email: "barcelona@tcgacademy.es",
    hours: "L-S 10:00-21:00 | D 11:00-19:00",
    mapUrl: "https://maps.google.com/?q=Pelai+Barcelona",
    color: "#7c3aed",
  },
];
